"""create events table

Revision ID: 55ddf91b135b
Revises: 
Create Date: 2026-08-15 22:05:53.407737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ddf91b135b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('process_pid', sa.Integer(), nullable=True),
    sa.Column('process_ppid', sa.Integer(), nullable=True),
    sa.Column('process_command_line', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_hash_sha256', sa.String(), nullable=True),
    sa.Column('network_source_ip', sa.String(), nullable=True),
    sa.Column('network_destination_ip', sa.String(), nullable=True),
    sa.Column('network_destination_port', sa.Integer(), nullable=True),
    sa.Column('network_protocol', sa.String(), nullable=True),
    sa.Column('raw_event', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
