"""create host_context table

Revision ID: 8ea3e8c8aff3
Revises: 9b849c1a9e38
Create Date: 2026-08-22 23:03:17.250122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea3e8c8aff3'
down_revision: Union[str, Sequence[str], None] = '9b849c1a9e38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_context',
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('host')
    )
    op.create_index(op.f('ix_host_context_criticality'), 'host_context', ['criticality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_context_criticality'), table_name='host_context')
    op.drop_table('host_context')
    # ### end Alembic commands ###
