"""create incident_clusters table

Revision ID: 9b849c1a9e38
Revises: 71361ab664ac
Create Date: 2026-08-17 14:57:58.766161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b849c1a9e38'
down_revision: Union[str, Sequence[str], None] = '71361ab664ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_clusters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_ids', sa.JSON(), nullable=False),
    sa.Column('detection_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('correlation_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_clusters_created_at'), 'incident_clusters', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_clusters_created_at'), table_name='incident_clusters')
    op.drop_table('incident_clusters')
    # ### end Alembic commands ###
