"""add indexes on timestamp, host, event_type

Revision ID: c00e64f9c194
Revises: 55ddf91b135b
Create Date: 2026-08-15 22:08:39.209668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c00e64f9c194'
down_revision: Union[str, Sequence[str], None] = '55ddf91b135b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_host'), 'events', ['host'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_host'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    # ### end Alembic commands ###
