"""create risk_assessments table

Revision ID: c2463c16304f
Revises: 8ea3e8c8aff3
Create Date: 2026-08-22 23:30:51.059460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2463c16304f'
down_revision: Union[str, Sequence[str], None] = '8ea3e8c8aff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('detection_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('host_criticality', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('override_risk_category', sa.String(), nullable=True),
    sa.Column('override_priority', sa.String(), nullable=True),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_detection_id'), 'risk_assessments', ['detection_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_priority'), 'risk_assessments', ['priority'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_category'), 'risk_assessments', ['risk_category'], unique=False)
    op.create_index(op.f('ix_risk_assessments_risk_score'), 'risk_assessments', ['risk_score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_risk_score'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_risk_category'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_priority'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_detection_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    # ### end Alembic commands ###
